"""LLM Analysis model — stores cycling performance analysis from Gemini."""

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class LlmAnalysis(Base):
    """Stores cycling stats analysis generated by an LLM (Google Gemini)."""

    __tablename__ = "llm_analyses"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    analysis_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    stats_json: Mapped[dict] = mapped_column(JSONB, nullable=False)  # compiled stats sent to LLM
    analysis_text: Mapped[str] = mapped_column(Text, nullable=False)  # LLM response
    model_used: Mapped[str] = mapped_column(String(100), nullable=False, default="gemini-2.0-flash")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    user: Mapped["User"] = relationship(back_populates="llm_analyses")  # type: ignore[name-defined]
