"""LLM Analysis model — stores cycling, lifting, health, and event performance analysis from Gemini."""

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

ANALYSIS_TYPE_OPTIONS = ("cycling", "activity", "lifting_session", "health", "event")


class LlmAnalysis(Base):
    """Stores performance analysis generated by an LLM (Google Gemini).

    Supports overall cycling performance analysis, per-activity analysis,
    per-lifting-session analysis, health analysis, and event preparation.
    When ``activity_id`` is set the analysis is specific to a single ride;
    when ``lifting_session_id`` is set it is specific to a single lifting session;
    when ``event_id`` is set it is specific to a single event.
    """

    __tablename__ = "llm_analyses"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    activity_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("activities.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    lifting_session_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lifting_sessions.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    event_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("events.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    analysis_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="cycling",
        index=True,
    )  # cycling, activity, lifting_session, health, event
    analysis_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    stats_json: Mapped[dict] = mapped_column(
        JSONB, nullable=False
    )  # compiled stats sent to LLM
    analysis_text: Mapped[str] = mapped_column(Text, nullable=False)  # LLM response
    model_used: Mapped[str] = mapped_column(
        String(100), nullable=False, default="gemini-2.0-flash"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    user: Mapped["User"] = relationship(back_populates="llm_analyses")  # type: ignore[name-defined]
