"""Nutrition models — ride fuel planning for cycling activities."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class RideFuelPlan(Base):
    """Fuel plan for a cycling ride — suggested targets plus logged actuals.

    A plan may be created ahead of a ride (activity_id null, planned duration/IF
    set) or after a ride completes (linked to the activity). The fuel schedule
    (timed carb/hydration/sodium suggestions) is generated by the service layer
    and stored in schedule_json for stable display.
    """

    __tablename__ = "ride_fuel_plans"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    activity_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("activities.id", ondelete="CASCADE"),
        nullable=True,
        unique=True,
        index=True,
    )

    # Planned inputs (used when generating the schedule)
    planned_duration_min: Mapped[int | None] = mapped_column(Integer, nullable=True)
    planned_if: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Suggested targets (computed by service)
    pre_ride_carbs_g: Mapped[float | None] = mapped_column(Float, nullable=True)
    during_carbs_per_hour_g: Mapped[float | None] = mapped_column(Float, nullable=True)
    during_hydration_ml_per_hour: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )
    during_sodium_mg_per_hour: Mapped[float | None] = mapped_column(Float, nullable=True)
    post_ride_carbs_g: Mapped[float | None] = mapped_column(Float, nullable=True)
    post_ride_protein_g: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Generated timeline: [{"time_min": 30, "carbs_g": 25, "hydration_ml": 250,
    #                        "sodium_mg": 125, "suggestion": "Gel + water"}, ...]
    schedule_json: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    # What was actually consumed (user fills in post-ride)
    actual_pre_ride_notes: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    actual_during_notes: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    actual_post_ride_notes: Mapped[str | None] = mapped_column(String(1000), nullable=True)

    source: Mapped[str] = mapped_column(
        String(20), nullable=False, default="auto"
    )  # auto (generated) | manual

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships
    user = relationship("User", back_populates="fuel_plans")  # type: ignore[name-defined]
